# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music player Ljm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music player Ljm

pod 'AFSoundManager'
pod 'Kingfisher'
pod 'Masonry', '~> 1.0.2'
pod 'SnapKit'


end
